name: Deploy to Production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: saat.hychin.tech
          port: 22
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/saat_attendance
            git fetch origin
            git checkout dev
            git pull origin dev
            npm install
            npm run build
            systemctl restart apache2
          debug: true
